# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.21

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Administrator\PL\sqrt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Administrator\PL\sqrt

# Include any dependencies generated for this target.
include CMakeFiles/../bin.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/../bin.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/../bin.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../bin.dir/flags.make

CMakeFiles/../bin.dir/src/a.obj: CMakeFiles/../bin.dir/flags.make
CMakeFiles/../bin.dir/src/a.obj: CMakeFiles/../bin.dir/includes_C.rsp
CMakeFiles/../bin.dir/src/a.obj: src/a.c
CMakeFiles/../bin.dir/src/a.obj: CMakeFiles/../bin.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\Administrator\PL\sqrt\CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/../bin.dir/src/a.obj"
	C:\ProgramData\chocolatey\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/../bin.dir/src/a.obj -MF CMakeFiles\..\bin.dir\src\a.obj.d -o CMakeFiles\..\bin.dir\src\a.obj -c C:\Users\Administrator\PL\sqrt\src\a.c

CMakeFiles/../bin.dir/src/a.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../bin.dir/src/a.i"
	C:\ProgramData\chocolatey\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\Administrator\PL\sqrt\src\a.c > CMakeFiles\..\bin.dir\src\a.i

CMakeFiles/../bin.dir/src/a.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../bin.dir/src/a.s"
	C:\ProgramData\chocolatey\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S C:\Users\Administrator\PL\sqrt\src\a.c -o CMakeFiles\..\bin.dir\src\a.s

CMakeFiles/../bin.dir/src/main.obj: CMakeFiles/../bin.dir/flags.make
CMakeFiles/../bin.dir/src/main.obj: CMakeFiles/../bin.dir/includes_C.rsp
CMakeFiles/../bin.dir/src/main.obj: src/main.c
CMakeFiles/../bin.dir/src/main.obj: CMakeFiles/../bin.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=C:\Users\Administrator\PL\sqrt\CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object CMakeFiles/../bin.dir/src/main.obj"
	C:\ProgramData\chocolatey\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/../bin.dir/src/main.obj -MF CMakeFiles\..\bin.dir\src\main.obj.d -o CMakeFiles\..\bin.dir\src\main.obj -c C:\Users\Administrator\PL\sqrt\src\main.c

CMakeFiles/../bin.dir/src/main.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../bin.dir/src/main.i"
	C:\ProgramData\chocolatey\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E C:\Users\Administrator\PL\sqrt\src\main.c > CMakeFiles\..\bin.dir\src\main.i

CMakeFiles/../bin.dir/src/main.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../bin.dir/src/main.s"
	C:\ProgramData\chocolatey\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S C:\Users\Administrator\PL\sqrt\src\main.c -o CMakeFiles\..\bin.dir\src\main.s

# Object files for target ../bin
__/bin_OBJECTS = \
"CMakeFiles/../bin.dir/src/a.obj" \
"CMakeFiles/../bin.dir/src/main.obj"

# External object files for target ../bin
__/bin_EXTERNAL_OBJECTS =

../bin.exe: CMakeFiles/../bin.dir/src/a.obj
../bin.exe: CMakeFiles/../bin.dir/src/main.obj
../bin.exe: CMakeFiles/../bin.dir/build.make
../bin.exe: CMakeFiles/../bin.dir/linklibs.rsp
../bin.exe: CMakeFiles/../bin.dir/objects1.rsp
../bin.exe: CMakeFiles/../bin.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=C:\Users\Administrator\PL\sqrt\CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Linking C executable ..\bin.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles\..\bin.dir\link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../bin.dir/build: ../bin.exe
.PHONY : CMakeFiles/../bin.dir/build

CMakeFiles/../bin.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles\..\bin.dir\cmake_clean.cmake
.PHONY : CMakeFiles/../bin.dir/clean

CMakeFiles/../bin.dir/depend:
	$(CMAKE_COMMAND) -E cmake_depends "MinGW Makefiles" C:\Users\Administrator\PL\sqrt C:\Users\Administrator\PL\sqrt C:\Users\Administrator\PL\sqrt C:\Users\Administrator\PL\sqrt C:\Users\Administrator\PL\sqrt\bin.dir\DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/../bin.dir/depend

